### ISSUE TITLE
Vultr结合SSR实现科学上网

### ISSUE THREAD

**Issue by RanrayD** [RanrayD/RanrayD.github.io#1]
最近公司原有的公共科学上网经常被封，需要去问别人好多次，感觉还是自己钓鱼自己吃比较踏实，所以想到了购买海外服务器+自行搭建梯子的方式。

### 购买一台海外服务器
购买链接：
`https://my.vultr.com/`
这里需要注意一点，购买服务器完毕后，去 https://www.vps234.com/ipchecker/ 测试一下 ip 有没有被墙 如果已经被墙，可以销毁后重新部署一台。
购买服务器无需多言，重点是下面的**自己搭建梯子的过程**

### 在海外服务器中配置ssr

**安装前最好先安装依赖包，配置好python 3.6 默认环境**

**先安装wget**
`yum -y install wget`

**安装ssr一键脚本管理**
`wget -N --no-check-certificate https://raw.githubusercontent.com/ToyoDAdoubi/doubi/master/ssr.sh && chmod +x ssr.sh && bash ssr.sh`

接下来是参数配置，配置好之后，启动可能会失败。以下是启动失败后需要注意的问题，解决问题的途径大都出现在这里

**Python导致的启动失败**
Vultr 上买的新服务器(centOS 8)虽然已经安装了 python36(若服务器没有安装 python 则需要先安装 python)，但没有配置为默认，因此 ssr 客户端会启动失败。
因此要先配置 Python36 为默认 Python
`alternatives --set python /usr/bin/python3`

**firewall导致的无法连接**
服务器默认开启了 firewall 防火墙，且默认没有开放任何端口，因此要将所配置的 ssr 端口(以443为例)添加到白名单并重启防火墙
```
firewall-cmd --add-port=443/tcp --permanent
firewall-cmd --add-port=443/udp --permanent
firewall-cmd --reload
```
**目前配置**
```
加密：aes-256-cfb
协议：origin
混淆：http_post
```
**后续管理&修改**
如果之后想修改账号信息，直接输入快捷管理命令：bash ssr.sh 进入管理界面，选择相应的数字来进行一键修改。例如：
![image](https://user-images.githubusercontent.com/35720612/101481614-69523080-3990-11eb-85df-99276023017b.png)

**Comment by kupao2015** [comment]
大佬，配置好以后还是本地的梯子还是不生效是什么原因呢？

**Comment by RanrayD** [comment]
> 大佬，配置好以后还是本地的梯子还是不生效是什么原因呢？

很遗憾我并没有解决这个问题的经验...
